### ISSUE TITLE
Feature request: integer types

### ISSUE THREAD

**Issue by kforner** [alexcb/rjson#15]
Hi,

I've seen that JSON officially defines the **integer** type (cf https://cswr.github.io/JsonSchema/spec/basic_types/#numeric-schemas).
Unless mistaken, rjson does not seem to support it (at least the integer variables are not output as JSON "integers").
It could be useful, `fromJSON(toJSON(x))` would be closer to the original.

**Comment by alexcb** [comment]
json schema is not part of the json spec; however, it still might be possible to try to use ints rather than floats whenever possible.

**Comment by kforner** [comment]
hmm right. 
How would you do it ? I guess that "1L" is not JSON compatible for instance ?

**Comment by alexcb** [comment]
Any numbers that don't contain a period could be converted into an int -- i think this simplification should only happen when simplify=TRUE.

json doesn't differentiate between ints and floats, since in javascript everything is a float.

I'll leave this open in case anyone wants to try implementing this.

**Comment by kforner** [comment]
Yes, makes perfect sense.
